services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Prometheus web UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus # Persistent metrics storage
    restart: unless-stopped

  express-server:
    build:
      context: . # Path to your Express app Dockerfile
      dockerfile: Dockerfile
    container_name: express-server
    ports:
      - "8080:8080" # Expose Express server on port 8080
    environment:
      - NODE_ENV=production
    depends_on:
      - prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana # Persistent storage
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

volumes:
  prometheus-data: # Persistent volume for Prometheus
  grafana-data: # Persistent volume for Grafana