services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Prometheus web UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus # Persistent metrics storage
    restart: unless-stopped

  express-server:
    build:
      context: . # Path to your Express app Dockerfile
      dockerfile: Dockerfile
    container_name: express-server
    ports:
      - "8080:8080" # Expose Express server on port 3000
    environment:
      - NODE_ENV=production
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus-data: # Persistent volume for Prometheus