name: Run Tests Before Deploying

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Adjust this to the Node.js version you are using

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # Step 2: Set up Node.js (adjust the version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
      # Step 4: Run tests
      - name: Run Tests
        run: npm test
      # Step 5: Deploy or make GET request
      - name: Make GET Request (if tests pass)
        if: success()
        run:
          curl -X GET ${{ secrets.R2_WEBHOOK_URL }}
