name: Run Tests Before Deploying

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Adjust this to the Node.js version you are using

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # Step 2: Set up Node.js (adjust the version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  # Adjust this to the Node.js version you are using
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
      # Step 4: Run tests
      - name: Run Tests
        run: npm test  # This assumes you are using jest as your test runner
      # Step 5: Deploy or make GET request (optional step)
      # Assuming you're deploying or calling an API after the tests pass
      - name: Make GET Request (if tests pass)
        if: success()  # This ensures the GET request is only made if tests are successful
        run: |
          curl -X GET ${{ secrets.R2_WEBHOOK_URL }}
